# Uncomment the next line to define a global platform for your project
  platform :ios, '8.0'

target 'KoreanLearning' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KoreanLearning
  pod 'lottie-ios'  
  pod 'WCDB'
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'pop'
  pod 'JLRoutes'
  pod 'YYKit'
 
  target 'KoreanLearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KoreanLearningUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
